title: Computational Thinking and Programming
description: A book for teaching Computer Science and Programming skills to people with a background in the Humanities
show_downloads: true
theme: jekyll-theme-hacker